### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1024 and 768x320)

### ISSUE THREAD

**Issue by theprogrammerknownasat** [MrForExample/ComfyUI-AnimateAnyone-Evolved#13]
I ran the included workflow and I got this error:

```got prompt
[rgthree] Using rgthree's optimized recursive execution.
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 152, in animate_anyone
    samples = diffuser(
  File "E:\Winget\py3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\main_diffuser.py", line 440, in __call__
    latents = self.denoise_loop(
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\main_diffuser.py", line 315, in denoise_loop
    self.reference_unet(
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 1197, in forward
    sample, res_samples = downsample_block(
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 657, in forward
    hidden_states, ref_feature = attn(
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 357, in forward
    hidden_states = block(
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\mutual_self_attention.py", line 241, in hacked_basic_transformer_inner_forward
    attn_output = self.attn2(
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Winget\py3\lib\site-packages\diffusers\models\attention_processor.py", line 527, in forward
    return self.processor(
  File "E:\Winget\py3\lib\site-packages\diffusers\models\attention_processor.py", line 1246, in __call__
    key = attn.to_k(encoder_hidden_states, *args)
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Winget\py3\lib\site-packages\diffusers\models\lora.py", line 430, in forward
    out = super().forward(hidden_states)
  File "E:\Winget\py3\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1024 and 768x320)

Prompt executed in 1.75 seconds
```

For reference I have the plugins: 
```   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds (IMPORT FAILED): F:\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui_lora_tag_loader
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: F:\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: F:\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: F:\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyI2I
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.2 seconds: F:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.5 seconds: F:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.6 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Manager
   1.2 seconds (IMPORT FAILED): F:\ComfyUI\custom_nodes\ComfyUI-ExLlama
   3.4 seconds: F:\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   3.7 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Crystools
   5.7 seconds: F:\ComfyUI\custom_nodes\was-node-suite-comfyui
   9.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
  12.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
  19.6 seconds: F:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
```

And I am running on a 3090.

I tried to update all [plugins and comfy] inside manager and I tried again on a fresh copy of comfy on a different OS (dual-boot windows twice) and got the same error. This second OS had a fresh install of python 3.10.6 and has never had torch or ComfyUI installed before.

I also know that this issue has already been brought up but was closed with no further information.

**Comment by adenek** [comment]
same here, looks like it could come for sd1.5 vs sdxl but after double checking, i don't think i do us any sdxl.

**Comment by sumeetprashant** [comment]
Hey Budd,

I had the same issue fixed it by using the correct clip vision model for Animate Anyone.
which is this one as stated on their github page.

https://huggingface.co/lambdalabs/sd-image-variations-diffusers/tree/main/image_encoder

Like me you also might be using the same old AnimateDiff clip vision SD model.

Hope this helps and fixes the issue,

Cheers

**Comment by adenek** [comment]
Yes I just saw it, was coming back here to said it :)
Thx

**Comment by theprogrammerknownasat** [comment]
Nevermind. It just randomly started working after hitting cue-prompt about ten times.

Thanks for your help!
