### ISSUE TITLE
An error occurs after installation.

### ISSUE THREAD

**Issue by toyxyz** [MrForExample/ComfyUI-AnimateAnyone-Evolved#2]
An error occurs after installation. The error message is as follows 

Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 23, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import PixArtAlphaTextProjection
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

**Comment by MrForExample** [comment]
This most likely means you have old version of `diffusers` installed.

Run `pip install --upgrade diffusers` in your ComfyUI python environment should solve this issue
