### ISSUE TITLE
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' 

### ISSUE THREAD

**Issue by ultimatech-cn** [MrForExample/ComfyUI-AnimateAnyone-Evolved#24]
Import failed when comfyUI starting:
Traceback (most recent call last):
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import PixArtAlphaTextProjection
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\embeddings.py)

Any solution for that?

**Comment by ech3lon42** [comment]
https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/issues/15

> You need to update " diffusers " to 0.25.1 , Eg. pip install --upgrade diffusers==0.25.1 will add the new embedding .. Then " PixArtAlphaTextProjection " can be found !

You may need to use the embedded python.

**Comment by MrForExample** [comment]
I updated the project to support newest diffuser v.0.26.1, I also updated the node reference in the example workflow, now it should works as intended.
So please update the addon and also update the diffuser package if you have same error:
`pip install --force-reinstall diffusers>=0.26.1`

**Comment by skynmu** [comment]
I tried to force-reinstall diffusers but received the following error:
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes>pip install --force-reinstall diffusers>=0.26.1
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pooch 1.7.0 requires platformdirs>=2.5.0, which is not installed.
google-auth 2.19.1 requires urllib3<2.0, but you have urllib3 2.2.0 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.3 which is incompatible.
scipy 1.9.3 requires numpy<1.26.0,>=1.18.5, but you have numpy 1.26.3 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.3 which is incompatible.

**Comment by skynmu** [comment]
Btw., I am trying to load your nodes (Animate Anyone and ComfyUI 3D pack) and keep getting the following error message: "When loading the graph, the following node types were not found:
[ComfyUI-3D] Animate Anyone Sampler
[ComfyUI-3D] Load UNet2D ConditionModel
[ComfyUI-3D] Load UNet3D ConditionModel
[ComfyUI-3D] Pose Guider Encode
[ComfyUI-3D] Load Pose Guider
Nodes that have failed to load will show as red on the graph."

**Comment by BrawnyAi** [comment]
The same here.
![dabeast](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/143237701/eff55bbc-4a8b-4cd4-b5a0-14d61c9736c0)

**Comment by chiragkrishna** [comment]
Solution: rebuild the nodes

- double click on canvas and search for "guider", you will find these
       - Pose Guider Encode
       - Load Pose Guider

- double click on canvas and search for "unet", you will find these
       -Load UNet2D ConditionModel
       -Load UNet3D ConditionModel

- double click on canvas and search for "animate", you will find
       - Animate Anyone Sampler

connect the red(failed nodes) to the new one and delete the old ones
