### ISSUE TITLE
'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by Bo0m974** [MrForExample/ComfyUI-AnimateAnyone-Evolved#53]
Total VRAM 8188 MB, total RAM 32454 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints E:\STABLE DIFF\Models\StableDiffusion
Adding extra search path vae E:\STABLE DIFF\Models\VAE
Adding extra search path loras E:\STABLE DIFF\Models\Lora
Adding extra search path loras E:\STABLE DIFF\Models\LyCORIS
Adding extra search path upscale_models E:\STABLE DIFF\Models\ESRGAN
Adding extra search path upscale_models E:\STABLE DIFF\Models\RealESRGAN
Adding extra search path upscale_models E:\STABLE DIFF\Models\SwinIR
Adding extra search path embeddings E:\STABLE DIFF\Models\TextualInversion
Adding extra search path hypernetworks E:\STABLE DIFF\Models\Hypernetwork
Adding extra search path controlnet E:\STABLE DIFF\Models\ControlNet
Adding extra search path controlnet E:\STABLE DIFF\Models\T2IAdapter
Adding extra search path clip E:\STABLE DIFF\Models\CLIP
Adding extra search path clip_vision E:\STABLE DIFF\Models\InvokeClipVision
Adding extra search path diffusers E:\STABLE DIFF\Models\Diffusers
Adding extra search path gligen E:\STABLE DIFF\Models\GLIGEN
Adding extra search path vae_approx E:\STABLE DIFF\Models\ApproxVAE
Adding extra search path ipadapter E:\STABLE DIFF\Models\IpAdapter
Adding extra search path ipadapter E:\STABLE DIFF\Models\InvokeIpAdapters15
Adding extra search path ipadapter E:\STABLE DIFF\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion E:\STABLE DIFF\Models\PromptExpansion
E:\STABLE DIFF\Packages\ComfyUI\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "E:\STABLE DIFF\Packages\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (E:\STABLE DIFF\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)

Cannot import E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (E:\STABLE DIFF\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - ERROR - No models available. Please download one and put it in models folder
Adding E:\STABLE DIFF\Packages\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.11)
Loaded ImpactPack nodes from E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Pack (V5.11)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.75)
Total VRAM 8188 MB, total RAM 32454 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
### ComfyUI Revision: 2225 [b1fd26fe] | Released on '2024-06-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ReActor] - STATUS - Running v0.5.0-b3 in ComfyUI
Torch version: 2.3.0+cu121
ERROR: Could not find a version that satisfies the requirement Comfyui-Toolbox (from versions: none)
ERROR: No matching distribution found for Comfyui-Toolbox
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
FizzleDorf Custom Nodes: Loaded
[R44]: Loaded Runtime44 nodes
Requirement already satisfied: segment_anything in e:\stable diff\packages\comfyui\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: torch in e:\stable diff\packages\comfyui\venv\lib\site-packages (from -r requirements.txt (line 2)) (2.3.0+cu121)
Requirement already satisfied: numpy in e:\stable diff\packages\comfyui\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: pillow in e:\stable diff\packages\comfyui\venv\lib\site-packages (from -r requirements.txt (line 4)) (10.2.0)
Requirement already satisfied: filelock in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (4.12.1)
Requirement already satisfied: sympy in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (1.12.1)
Requirement already satisfied: networkx in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: jinja2 in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.1.3)
Requirement already satisfied: fsspec in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (2024.5.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in e:\stable diff\packages\comfyui\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in e:\stable diff\packages\comfyui\venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->-r requirements.txt (line 2)) (2021.4.0)
Requirement already satisfied: tbb==2021.* in e:\stable diff\packages\comfyui\venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->-r requirements.txt (line 2)) (2021.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\stable diff\packages\comfyui\venv\lib\site-packages (from jinja2->torch->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in e:\stable diff\packages\comfyui\venv\lib\site-packages (from sympy->torch->-r requirements.txt (line 2)) (1.3.0)
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 76 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://120.0.0.0.0mtb if you want more information.

[rgthree] Loaded 39 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 213 nodes successfully.

	"Success is not about being better than someone else. It's about being better than you used to be." - Unknown

Import times for custom nodes:
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\chatbox_overlay.py
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\Comfyui-Yolov8
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui_face_parsing
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui_r44_nodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-quadMoons-nodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\segment_to_mask_comfyui
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-reproduction
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-aichemy-nodes
   0.1 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.2 seconds (IMPORT FAILED): E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
   0.2 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.3 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui-art-venture
   0.6 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\a-person-mask-generator
   0.9 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfyui-reactor-node
   1.0 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\Comfyui-Yolov8-JSON
   1.3 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.4 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\comfy_mtb
   1.8 seconds: E:\STABLE DIFF\Packages\ComfyUI\custom_nodes\ComfyUI_Segment_Mask

Starting server

**Comment by Bo0m974** [comment]
trouver c'etait ceci [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack)
