### ISSUE TITLE
Error in loading the module: ImportError: cannot import name 'LCMScheduler' from 'diffusers.schedulers'

### ISSUE THREAD

**Issue by faux123** [MrForExample/ComfyUI-AnimateAnyone-Evolved#6]
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 11, in <module>
    from diffusers.schedulers import (
ImportError: cannot import name 'LCMScheduler' from 'diffusers.schedulers' (G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\__init__.py)

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers.schedulers' (G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\__init__.py)

**Comment by CambridgeComputing** [comment]
I had the same error, resolved by updating `diffusers`:
`pip install --upgrade diffusers`

https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/issues/2#issuecomment-1901089199
